### ISSUE TITLE
Filtering by time of day

### ISSUE THREAD

**Issue by Vollpflock** [Mattk70/Chirpity-Electron#100]
**Is your feature request related to a problem? Please describe.**
When I'm recording 24/7, I analyze the files using the local bird list. For certain species, I'm specifically interested in nocturnal calls. Additionally, some species are likely to be active only at night, which means I wouldn't have to sift through as many recordings. 

**Describe the solution you'd like**
Within the archive feature, alongside the 'Apply date filter,' I would appreciate having an additional filter option for time of day. No need for sunrise/sunset. 

**Alternatives**
Re-analyzing the files using the nocturnal bird list. That messes up my archive, though.

**Comment by Mattk70** [comment]
There are two ways to do this already. The first is to switch to the 'nocturnal birds' list whilst viewing your archive. The second is to use the date filter to restrict the time to a night time period: you can enter a time of day in the date filter.

**Comment by Vollpflock** [comment]
Wow, I didn't realize that. Switching to the 'nocturnal birds' list while viewing my archive is already pretty good. However, it seems like the second option (using the date filter to restrict the time to nighttime) only works for one day, right? For example, if I put in 5th April 10 PM to 10th April 2 AM, it displays the entire time between those, including, say, 3 PM. But that doesn't matter much. I don't want to waste your time with something so minor.
