### ISSUE TITLE
Does not save location

### ISSUE THREAD

**Issue by Vollpflock** [Mattk70/Chirpity-Electron#101]
**Describe the bug**
I don't know when it saved the few locations that I have in the Archive, but it generally doesn't save locations.

**To Reproduce**
See screenshots below.

**Expected behavior**
It should save the location (the name I gave and the coordinates). 

**Screenshots**
The first test (Amend File Recording Location before analysis)
![Screenshot 2024-04-13 at 13 16 02](https://github.com/Mattk70/Chirpity-Electron/assets/26574621/a4787f07-e20f-4058-954b-aa675f6bbef2)
![Screenshot 2024-04-13 at 13 16 48](https://github.com/Mattk70/Chirpity-Electron/assets/26574621/667a156f-ebdc-4f50-8118-a783a41fa0ab)
![Screenshot 2024-04-13 at 13 17 07](https://github.com/Mattk70/Chirpity-Electron/assets/26574621/52f690d5-d04f-45d9-8e88-1537b4fc0fea)
![Screenshot 2024-04-13 at 13 17 15](https://github.com/Mattk70/Chirpity-Electron/assets/26574621/bbd10ff5-8ed0-4145-894d-3b6135345a7f)
![Screenshot 2024-04-13 at 13 17 52](https://github.com/Mattk70/Chirpity-Electron/assets/26574621/2f34c175-34b6-4a26-8ba0-f68bc4140a13)
![Screenshot 2024-04-13 at 13 18 14](https://github.com/Mattk70/Chirpity-Electron/assets/26574621/121ef168-8576-4124-9e79-562c95e43b71)
![Screenshot 2024-04-13 at 13 18 36](https://github.com/Mattk70/Chirpity-Electron/assets/26574621/421578fe-b549-49e0-8c32-615b437f5111)

The second test (Amend File Recording Location after analysis)
![Screenshot 2024-04-13 at 13 33 01](https://github.com/Mattk70/Chirpity-Electron/assets/26574621/cf84cfbf-325b-4e8f-8d24-69af8ab59ccf)
![Screenshot 2024-04-13 at 13 33 50](https://github.com/Mattk70/Chirpity-Electron/assets/26574621/59991f29-d4fe-4713-be15-ed68d4e7787d)
![Screenshot 2024-04-13 at 13 34 01](https://github.com/Mattk70/Chirpity-Electron/assets/26574621/a6472618-d61f-4553-8801-9fd31d711fe5)
![Screenshot 2024-04-13 at 13 34 38](https://github.com/Mattk70/Chirpity-Electron/assets/26574621/2c4b42b5-ac10-4e45-9d7f-5f1208ca41a2)
![Screenshot 2024-04-13 at 13 34 48](https://github.com/Mattk70/Chirpity-Electron/assets/26574621/6df0d071-18d7-42bc-b469-2f2520a946db)
![Screenshot 2024-04-13 at 13 35 37](https://github.com/Mattk70/Chirpity-Electron/assets/26574621/2a787ee3-77d3-4fed-ab9b-bb5d3e77823c)

**Additional context**
This has already been mentioned in https://github.com/Mattk70/Chirpity-Electron/issues/66. It happens to me with "Analyze" as with "Re-Analyze".

**Comment by Mattk70** [comment]
So, I think it does save the locations, but here's what I think is happening:

In the first test, you set a location for a file whose results you do not save. The location for this file is stored in memory, and only committed (saved to the archive) when you save the records.

In the second test, the location _is_ saved, but the location list does not update immediately. Can you verify this is what's happening? If you were to select Records > Explore Archive again, is the location now present?

**Comment by Vollpflock** [comment]
Well that was stupid. You're completely right. 

However, there's another (very small) issue. When I right click on a file and choose "Amend File Recording Location", it shows me a map with the locations. However, if I click on an existing location, it doesn't show me the name I gave it. F.e. here, I analyzed a file and gave it the name "Geneva Zentrum". But now it says "Petit-Lancy, Lancy".

**Comment by Mattk70** [comment]
Hmm, yes, I think that'll be because when you click the map, it gets the name from the map API, not the name you saved.
