### ISSUE TITLE
Timeline switches from "Time of day" to "Timecode"

### ISSUE THREAD

**Issue by Vollpflock** [Mattk70/Chirpity-Electron#104]
**Describe the bug**
Timeline sometimes switches from "Time of day" to "Timecode". 

**To Reproduce**
I don't know exactly when it happens.

**Expected behavior**
Should not switch automatically between "Time of day" and "Timecode". 

**Additional context**
Again, very very minor.

**Comment by Mattk70** [comment]
You may be hitting option T? That's a keyboard shortcut to switch between the two time modes.

**Comment by Vollpflock** [comment]
Not sure. But that's already enough, that way I don't need to go into settings every time.
