### ISSUE TITLE
Retrieve results for multiple files

### ISSUE THREAD

**Issue by Vollpflock** [Mattk70/Chirpity-Electron#105]
**Is your feature request related to a problem? Please describe.**
This has to do with location data not being saved correctly (https://github.com/Mattk70/Chirpity-Electron/issues/101). I have recordings from various locations and need to organize them accordingly. Since my folder structure already separates them, I'd like Chirpity to allow me to open all files within a folder and display all the detections associated with it. Even if https://github.com/Mattk70/Chirpity-Electron/issues/101 gets resolved, I would like to have this option to quickly access detections or to change the location in retrospect.

**Describe the solution you'd like**
Retrieving results for multiple files (not just one file).

**Describe alternatives you've considered**
Locations getting saved (https://github.com/Mattk70/Chirpity-Electron/issues/101).

**Additional context**

**Comment by Mattk70** [comment]
So, I think you can do this by opening the folder from a location. If all the files you open are saved in the database, you will be able to 'retrieve results'. However if there is just one file amongst them which is not saved, you won't have this option.

**Comment by Vollpflock** [comment]
That doesn't work in my case, I tested it using two files that were already analyzed and it showed only the results from the first file when I opened both files and hit "Retrieve Results".

Btw, I just saw that it sets the "created date" when the file ended. F.e. when my file is 1 hour long and I started recording at 3 pm, it sets the created date to 4pm... I maybe need to run a script first to set recording date one hour back before opening them in chirpity. Otherwise, it messes up "nocturnal" mode. 

![Screenshot 2024-04-13 at 17 19 50](https://github.com/Mattk70/Chirpity-Electron/assets/26574621/3ce15f32-32c4-4812-a60b-ff8535d0366f)
![Screenshot 2024-04-13 at 17 19 57](https://github.com/Mattk70/Chirpity-Electron/assets/26574621/b5a4c6a1-a206-4026-b552-944584903b39)
![Screenshot 2024-04-13 at 17 20 29](https://github.com/Mattk70/Chirpity-Electron/assets/26574621/f7f95e90-1540-477e-bd3d-3d78b37991b5)
![Screenshot 2024-04-13 at 17 20 50](https://github.com/Mattk70/Chirpity-Electron/assets/26574621/3ee9e73e-4a8a-4819-a6a2-759a5f65f4be)
![Screenshot 2024-04-13 at 17 20 57](https://github.com/Mattk70/Chirpity-Electron/assets/26574621/3af3a2f9-e4e3-4fc5-a1c9-9a171e67c3fb)
![Screenshot 2024-04-13 at 17 21 02](https://github.com/Mattk70/Chirpity-Electron/assets/26574621/930f7b1c-661d-4228-b1b4-af409b712f00)

**Comment by Mattk70** [comment]
Ah, yes. My mistake. You have to hit "Analyse all open files". It won't. It will get the results from the database, if all the files have been previously analysed. I should really change the menu item for both "Analyse file" _and_ "Analyse all open files" when all files are saved.

**Comment by Mattk70** [comment]
> Btw, I just saw that it sets the "created date" when the file ended. F.e. when my file is 1 hour long and I started recording at 3 pm, it sets the created date to 4pm... I maybe need to run a script first to set recording date one hour back before opening them in chirpity. Otherwise, it messes up "nocturnal" mode.

Chirpity looks at "modified date"  for nocmig mode, then works out the start time from the files' duration.

**Comment by Vollpflock** [comment]
amazing

**Comment by Mattk70** [comment]
> Btw, I just saw that it sets the "created date" when the file ended. F.e. when my file is 1 hour long and I started recording at 3 pm, it sets the created date to 4pm... I maybe need to run a script first to set recording date one hour back before opening them in chirpity. Otherwise, it messes up "nocturnal" mode.

Is this related to Daylight Saving Time? Is the time on your recorder correct?

**Comment by Vollpflock** [comment]
I'm not sure if it actually messes up Daylight Saving Time. Yes, the time on my recorders are correct.
