### ISSUE TITLE
Change location name 

### ISSUE THREAD

**Issue by Vollpflock** [Mattk70/Chirpity-Electron#107]
**Is your feature request related to a problem? Please describe.**
I need to change some location names to keep it organized.

**Describe the solution you'd like**
In Archive, right-click on a location and change it's name.
Or if that's not possible: In Archive, select a location, click on the files and on "Amending file recording location" (without having to Re-Analyze all files).

**Describe alternatives you've considered**
Re-Analyzing the files and Amending file recording location. 

**Additional context**
This has already been mentioned under https://github.com/Mattk70/Chirpity-Electron/issues/105.

**Comment by Mattk70** [comment]
You can do this. Ideally open a file from the location whose name you want to change.

1. Right click on the filename in the panel. 
2. Choose the location to change. 
3. Change the name, hit "Set location". 
4. Reselect "Records > Explore Archive" to see the updated name in the list.

**Comment by Vollpflock** [comment]
You're right, I just tested this twice. But one time, I had both location names, the old one wasn't deleted. The other time, the old one was deleted. Maybe because I hit cmd+S the second time?

**Comment by Mattk70** [comment]
I don't know. Perhaps the locations were in slightly different positions?

**Comment by Vollpflock** [comment]
That could be, not sure though. I'll close the issue and come back if that happens again
