### ISSUE TITLE
Feature Request : Add Markers Export for Adobe Audition

### ISSUE THREAD

**Issue by CountryTec** [Mattk70/Chirpity-Electron#111]
**Is your feature request related to a problem? Please describe.**
Not a problem, Audacity integration works fine, but am very familiar with Audition and like usability and features there

**Describe the solution you'd like**
Would be cool to have an Export feature to Audition. The link below describes the layout. It's CSV as well, quite close to Audacity, but different. Tried to lookup and link and change in Excel, but failed.

**Describe alternatives you've considered**
I can continue with Audacity clearly. But if you can add this, that would be great. No hurry - season is continuing, some birds will just come in few days, others have left the region direction North.

**Additional context**
[[Add any other context or screenshots about the feature request here.](https://larryjordan.com/articles/adobe-audition-cc-how-to-share-markers-between-projects/)](https://larryjordan.com/articles/adobe-audition-cc-how-to-share-markers-between-projects/)

**Comment by Mattk70** [comment]
Hey. I guess firstly, I am curious as to the advantages of reviewing your detections in Audition or Audacity, I've used Audacity and navigating through labels to see what was detected at that point in the file is a pain. There's no way to filter by species or sort by detection confidence, it's difficult to establish the time of day for calls. I've really only kept the export Audacity labels option for legacy reasons - when I first built the app it had no way to filter by species or sort detections.

I do appreciate there are more audio filters and  the option to export audio to more formats - is that the draw? Or is it that some of the measurement features are better - call frequency and duration  You can do this in Chirpity, but I fear these features are not apparent.
