### ISSUE TITLE
Selecting Existing Location not working

### ISSUE THREAD

**Issue by Vollpflock** [Mattk70/Chirpity-Electron#112]
**Describe the bug**
Coordinates do not change when selecting an existing location. 

**To Reproduce**
See screenshots below

**Expected behavior**
Coordinates should change when selecting an existing location. 

**Screenshots**
![Screenshot 2024-04-15 at 08 18 31](https://github.com/Mattk70/Chirpity-Electron/assets/26574621/424f1c24-4e30-4258-916f-ec2572456f01)
![Screenshot 2024-04-15 at 08 18 38](https://github.com/Mattk70/Chirpity-Electron/assets/26574621/8338369c-43f4-41ae-8a4e-c21ed312258b)
![Screenshot 2024-04-15 at 08 18 49](https://github.com/Mattk70/Chirpity-Electron/assets/26574621/310bbefe-6ea6-41d2-9180-519add3e78b4)

**Comment by Mattk70** [comment]
Fixed in 1.7.0

**Comment by Vollpflock** [comment]
Bavissimo!

**Comment by Mattk70** [comment]
Ha! Thanks.
