### ISSUE TITLE
Capital letters in Swedish species names

### ISSUE THREAD

**Issue by Svardsten53** [Mattk70/Chirpity-Electron#116]
**Describe the bug**
Swedish species names do not have capital letters.

**To Reproduce**
NA

**Expected behavior**
Capital letter in the beginning of species names. The naming standard should be the same as for the scientific names.

**Screenshots**
NA

**Additional context**
I have managed to have this fixed in BirdNET-Pi, BirdWeather and now also BirdNET-Analyser where I guess several other apps are fetching the species lists. Please see https://github.com/kahst/BirdNET-Analyzer/issues/293
Thank you!

**Comment by Mattk70** [comment]
Hey Tim, quick response: Sure it'll be easy enough to capitalise the names. However, you know, all these apps get their translated species names from eBird. If you want to fix the issue at source, that's where you should get the translation fixed.

If you don't get it chaged there, the next time a BirdNET model is updated with new species, they'll pull in a new set of translations from eBird, and all these apps will update their lists with new files, with the lowercase Swedish names.

**Comment by Mattk70** [comment]
I have a question. Should both names be capitalised? Here is an example from the latest BirdNET Swedish translation:

Accipiter cirrocephalus_Australisk sparvhök

Is this correct, or should it be:

Accipiter cirrocephalus_Australisk Sparvhök

?

For now I will mimic the BirdNET translations

**Comment by Mattk70** [comment]
Done in release 1.7.2

**Comment by Svardsten53** [comment]
I installed 1.7.2 and it works! First you had to change language settings to another country and then back to your own again. Can be good to know.
