### ISSUE TITLE
Cannot perform Construct on a detached ArrayBuffer

### ISSUE THREAD

**Issue by Vollpflock** [Mattk70/Chirpity-Electron#120]
**Describe the bug**
Analysis gets stuck in V1.7.2. It's working well in V1.7.0.

**To Reproduce**
1. Tried to analyze 20 m4a files

**Screenshots**
![Screenshot 2024-04-20 at 08 14 06](https://github.com/Mattk70/Chirpity-Electron/assets/26574621/1604eb32-6665-4012-b75a-5a0dc0409b7d)

**Additional context**
V1.7.2
M1 mac
m4a files

**Comment by Mattk70** [comment]
This looks like a memory problem (RAM, not hard disk space).  Am I correct in inferring the following:

Model: BirdNET
Threads: 7
Audio files' duration: c. 1 hour each
Batch size: either 16 or 64 - do you recall the setting used when the error occurred?
Just **one** window open

How far into the analysis were you when it appeared to halt - or these errors started to appear - was it near the end or near the beginning of the analysis?

I'll see if I can replicate this on my Mac, How much RAM does your Mac have, incidentally?

**Comment by Vollpflock** [comment]
Correct (birndet, 7 threads, audio files 1 hour long, 25 files, batch size 16, one window open). It happened at around file 5 or 10, I think. It got stuck completely at file 20. 16 GB RAM

**Comment by Mattk70** [comment]
Can you let me know if this still happens in version 1.8.0?

**Comment by Vollpflock** [comment]
Yes, still happens under 1.8.0. I used the same settings as last time. It analyzed up to file 14/46.

![Screenshot 2024-04-24 at 19 48 58](https://github.com/Mattk70/Chirpity-Electron/assets/26574621/e17ccbb9-927a-4d45-9ffb-4d8a912e3745)

**Comment by Mattk70** [comment]
OK, similar issues were caused for Windows builds when using the latest version of node, so I have downgraded node on my mac and rebuilt the app. Could you give this pre-release a try? Thanks! https://github.com/Mattk70/Chirpity-Electron/releases/tag/v1.8.1

**Comment by Vollpflock** [comment]
Great - it orks under 1.8.1 and batch size 32. Haven't tried other batch sizes.

**Comment by Mattk70** [comment]
Awesome! That was a hideous bug to track down.

**Comment by Vollpflock** [comment]
It does not work with batch size 16, though. At batch size 16 (and 9 threads), % CPU is at a constant 500-550. However, it gets stuck. Maybe I should switch back to WAV. But for that I would need other recording devices with more storage.

**Comment by Mattk70** [comment]
I still think this is fundamentally a memory issue. I'll put a limit on the backlog of audio, it should prevent audio buffers filling up the avaialble memory while waiting for the predictions to be processed.

**Comment by Vollpflock** [comment]
But why does it work under v1.7.0 and older?

**Comment by Mattk70** [comment]
Not sure, or even sure if it did. However, I traced a source of detached ArrayBuffers to a function in Node. I have written a new function to avoid using it, and it seems to have fixed the problem in 1.9.0.

**Comment by Vollpflock** [comment]
Seems to be working now, thank you!
