### ISSUE TITLE
Performance seems to spike up and then drop again

### ISSUE THREAD

**Issue by Vollpflock** [Mattk70/Chirpity-Electron#123]
**Describe the bug**
Not sure why, but performance seems to spike up and then drop again. I'm pretty sure that wasn't a problem in older versions. It may also have to do with the m4a format.

**To Reproduce**
1. Analyze all files

**Expected behavior**
It should be at a constantly high % CPU.

**Screenshots**
![Screenshot 2024-04-25 at 08 14 42](https://github.com/Mattk70/Chirpity-Electron/assets/26574621/f475d68d-0785-4dae-8ada-87b2641a223f)
![Screenshot 2024-04-25 at 08 14 55](https://github.com/Mattk70/Chirpity-Electron/assets/26574621/19e167f8-0458-4eb5-a8df-2102bff539be)
![Screenshot 2024-04-25 at 08 15 00](https://github.com/Mattk70/Chirpity-Electron/assets/26574621/c333a0ed-088b-4245-8e4b-7b683d4a596a)
![Screenshot 2024-04-25 at 08 15 05](https://github.com/Mattk70/Chirpity-Electron/assets/26574621/ec54a532-ea82-42ee-8805-984c18b12078)
![Screenshot 2024-04-25 at 08 15 16](https://github.com/Mattk70/Chirpity-Electron/assets/26574621/fbdc67e8-4c18-4a3d-ac4e-9b8d6e243475)
![Screenshot 2024-04-25 at 08 15 20](https://github.com/Mattk70/Chirpity-Electron/assets/26574621/653a257b-011f-4552-834a-53e77d583653)
![Screenshot 2024-04-25 at 08 15 26](https://github.com/Mattk70/Chirpity-Electron/assets/26574621/615c1fd7-c9d7-451e-a08d-4e2ed3d31443)
![Screenshot 2024-04-25 at 08 15 30](https://github.com/Mattk70/Chirpity-Electron/assets/26574621/305e44f3-8715-49aa-8169-6b5129368ca5)
![Screenshot 2024-04-25 at 08 15 36](https://github.com/Mattk70/Chirpity-Electron/assets/26574621/7a2b03bc-1293-49b0-8a08-57dcfe66ac51)
![Screenshot 2024-04-25 at 08 15 42](https://github.com/Mattk70/Chirpity-Electron/assets/26574621/b7dc36e6-4266-4f7a-94e3-6ff2bcbc467d)
![Screenshot 2024-04-25 at 08 15 45](https://github.com/Mattk70/Chirpity-Electron/assets/26574621/0d650c80-5f4d-4f8e-8e86-8619f6d5ab48)

**Additional context**
Mac
v1.8.1
M4a
7 threads
32 batch size

**Comment by Mattk70** [comment]
If you look at the performance tab of the debug console, and start a recording whilst the application is analysing, you'll see something like this, after you hit stop:

<img width="600" alt="image" src="https://github.com/Mattk70/Chirpity-Electron/assets/61826357/2e17b160-8ab3-4535-bba1-f3df5f99f199">

This profile shows that the main process is the bottleneck, and the workers doing predictions are idle a lot of the time. If I run the profiler with a batch size of 16, the main thread is still the bottleneck, but the workers are busy more of the time:

<img width="635" alt="image" src="https://github.com/Mattk70/Chirpity-Electron/assets/61826357/ea229c53-c7c8-4c53-8b1a-96d62ec23ec5">

And if I use the Chirpity model, with those settings, the main thread isn't a bottleneck, and all the little workers are maxxed out:
<img width="630" alt="image" src="https://github.com/Mattk70/Chirpity-Electron/assets/61826357/3d879390-9f16-4d69-8b49-b58fb148309c">

I'm not really sure why at this point, but I suggest you use a lower batchsize for m4a files, and re-consider the chirpity model
