### ISSUE TITLE
Grey highlight rectangle stays on screen

### ISSUE THREAD

**Issue by Akseli-Ilmanen** [Mattk70/Chirpity-Electron#126]
**Describe the bug**
When highlighting part of the spectrogram, the grey rectangle remains on top of the image. After highlighting a couple of locations, the spectrogram is full of the grey rectangles (see screenshot). The grey rectangles remain even after opening another file.

**To Reproduce**
1. Left click and hold and drag to highlight part of spectrogram
2. Repeat

**Screenshots**
![image](https://github.com/Mattk70/Chirpity-Electron/assets/107996462/ab17dfc2-ad94-4d8d-80c2-c393421839c7)

![image](https://github.com/Mattk70/Chirpity-Electron/assets/107996462/bfd9ca89-3e5e-48eb-be0b-a623a62c6673)

**Comment by Mattk70** [comment]
Oooh. That doesn't look right!

I tried: 
1. open a file
2. drag out a selection
3. repeat 2 somewhere else on the spectrogram.

That works as expected for me. The initial selection is cleared and a new one created.

If you do that, do you get two selections? Does it happen all the time, or just every now and again?

**Comment by Akseli-Ilmanen** [comment]
Hi! Thanks for the quick reply.

Yes, I get two selections, and then more if I do more selections. It happens every time.

I have uninstalled and then installed 1.10.1 but the issue still remains.

Best
Akseli

**Comment by Akseli-Ilmanen** [comment]
Okay, after reinstalling and then restarting my PC, the issue is gone. Thanks for the help and for chirpity!:)

**Comment by Mattk70** [comment]
That's good to hear! I had a look at the code and can see how this might happen. Let me know if it comes back as an issue.

**Comment by Mattk70** [comment]
I discovered that sometimes the WaveSurfer library (used for the spectrogram and these highlighted regions) creates two regions instead of one. I don't know why that is or why the second region is not registered. When they are cleared, only the registered one is removed, so they build up. I have now added a check for these extra regions and clear them if they exist.
