### ISSUE TITLE
howcome this 

### ISSUE THREAD

**Issue by JoostvanBruggen** [Mattk70/Chirpity-Electron#129]
Howcome that during the main analysis from last night a Spotted Crake that flew by at 04:13hr was not identified as such but as a probable Quail. But while analyzing the call manually it said a max of 31% sure for Spotted Crake... It was definitely a Spotted Crake.
This way I can't trust any outcome. There could be Spotted Crakes in my prior nights. I might have missed more Little Bitterns etc.

Why is there a difference in the automated analysis and the manual one?

I have put the confidence level now to 0,01 so I get as many false positives (I think) as possible but this one still wasn't found.

![no spotted crake](https://github.com/Mattk70/Chirpity-Electron/assets/166588497/28393c16-24fa-4dc2-861f-8510d79449f5)

**Comment by Mattk70** [comment]
Hi @JoostvanBruggen, this is a very similar question to the one you asked here: https://github.com/Mattk70/Chirpity-Electron/discussions/91. In my response to that query, I tried to account for the different confidence values for the two approaches. 

Thinking specifically about Spotted Crake / Quail - we know the Quail typically emits 3 calls in succession, but imagine this: during training, there will be training examples used that clip the call so only one of the notes is present. A single note from a quail wet-my-lips call is superficially similar to the single whip call of a spotted crake. This will be why the model sometimes confuses the species. 

From the first screenshot, I can see the crake detection has 4 possibilities (denoted by the grey circle with a 4 in it) that reach a confidence value above the selected 15% threshold. If you click that circle, you can see what these are. It would not surprise me at all if one of these was Quail.

Incidentally, I cannot see either of the calls clearly in the highlighted regions of the spectrograms, if I was doing a manual search I doubt I would have paused to listen at that point! Anyway, these models are great at detecting sound events, but less assured in identification. Let's imagine these models are 99% accurate (which they aren't). This sounds phenomenal on paper, but in reality, when it makes 1200 predictions an hour, it's going to get 12 wrong. So, can you trust that all the detections are correctly identified without verifying yourself? Absolutely not! In spite of this, is it a useful tool? I think so, especially for less experienced nocmiggers, but you'll have your own view.

**Comment by Mattk70** [comment]
Closing issue as stale.
