### ISSUE TITLE
Time is not correct for mainland Europe

### ISSUE THREAD

**Issue by JoostvanBruggen** [Mattk70/Chirpity-Electron#130]
There is still a difference between the actual time of the recording, for instance started last night at 22:50 but the table with all calls starts at 23:50.
I have to change the time of all saved recordings and on Trektellen.com i have to keep in mind that the time is minus one hour.

Can this be canged?

**Comment by Mattk70** [comment]
Are you using version 1.10.2? 

The table and the timeline above the spectrogram display the time in your local time zone (as set on your computer). Prior to 1.10.2, exported detections were using GMT/UTC. I have fixed this to display local time in the exports to CSV , and single audio files, but with batch audio exports, the filename is still UTC. I'll fix that in the next release.

**Comment by Mattk70** [comment]
This has been addressed in https://github.com/Mattk70/Chirpity-Electron/releases/tag/v1.10.3
