### ISSUE TITLE
Problem with audio clips export

### ISSUE THREAD

**Issue by LAURASOLEB** [Mattk70/Chirpity-Electron#131]
**First steps**
Let us know a little about your setup. Ideally, provide a screenshot of the window which appears when you choose  Help > Diagnostics in the menu will often be useful - as it captures all the relevant  system and settings information. Minimally, please let us know:
![Diagnostics_Chirpity](https://github.com/Mattk70/Chirpity-Electron/assets/172253054/bb805119-f440-4db7-aad8-8431f8cfed23)

*Chirpity version: 1.7.2
*Operating system (PC/Mac): Windows 10 Pro

**Describe the bug**
I processed my folder with audio files (109 GB in size), introducing a custom list with two species (Green Sandpiper and Water Rail). When the processing was finished, I selected one of the species to export the chunks and performed the manual validation. At the top right of my screen, a message appeared saying that all the files had been saved in my folder, but in reality, the folder is empty. The disk where I want to save the chunks has 1.58 TB available, so I don't think the problem is memory. Do you know what other problem could be occurring? Thank you very much.

**What steps cause the issue?**
Describe the steps followed to reproduce the problem, for example:
1. Launch Chirpity
2. Click one species on the left results list
3. Click on "Export audio clips"
4. The chunks are nos available in my outputs folder

**Expected behaviour**
May be it could be due to the disk memory, but it has 1.58 TB available.

**Screenshots**

**Additional context**
The analyzed files are in .wav format and are 30 minutes long.

**Comment by Mattk70** [comment]
Hi @LAURASOLEB, I think the problem you are having is because Chirpity is unable to locate the original audio files ( I can see about 1000 "file not found" errors in my logs). Did you disconnect the drive / move or rename these files after the analysis?

Also, you are using an old version of Chirpity, which has a bunch of bugs that have been fixed since. 1.10.2 is the latest version.

**Comment by LAURASOLEB** [comment]
Hi Matt,

Thank you for your response.

I did not disconnect my disk nor rename the audio files.

I have done more tests, and I was able to extract the chunks from one of my two target species, but from the other species, I can only extract 250 chunks out of the total 7,743 detections.

I’m going to update the Chirpity version, but I don’t know if the results will be saved or if I will have to process the audio files again.

If the problem persists, do you know another reason why this could be happening?

Thank you,
Laura

De: Mattk70 ***@***.***>
Enviado el: lunes, 10 de junio de 2024 13:05
Para: Mattk70/Chirpity-Electron ***@***.***>
CC: Laura Solé ***@***.***>; Mention ***@***.***>
Asunto: Re: [Mattk70/Chirpity-Electron] Problem with audio clips export (Issue #131)


Hi @LAURASOLEB<https://github.com/LAURASOLEB>, I think the problem you are having is because Chirpity is unable to locate the original audio files ( I can see about 1000 "file not found" errors in my logs). Did you disconnect the drive / move or rename these files after the analysis?

Also, you are using an old version of Chirpity, which has a bunch of bugs that have been fixed since. 1.10.2 is the latest version.

**Comment by Mattk70** [comment]
Hi @LAURASOLEB, updating the application will not affect any records saved to your archive. There **is** a limit of 1,000 files in the export. 1,000 audio files was more than I'd imagined someone would want to export in one go! If you want to export more than this, I suggest you use a date filter to limit each export to <1000 files, and adjust that filter until you have moved through all the records.

**Comment by LAURASOLEB** [comment]
Hi Matt,

Thanks for this information. I'm going to try what you suggested and I will let you know if the result is successful.

Best regards,
Laura

De: Mattk70 ***@***.***>
Enviado el: lunes, 10 de junio de 2024 18:03
Para: Mattk70/Chirpity-Electron ***@***.***>
CC: Laura Solé ***@***.***>; Mention ***@***.***>
Asunto: Re: [Mattk70/Chirpity-Electron] Problem with audio clips export (Issue #131)


Hi @LAURASOLEB<https://github.com/LAURASOLEB>, updating the application will not affect any records saved to your archive. There is a limit of 1,000 files in the export. 1,000 audio files was more than I'd imagined someone would want to export in one go! If you want to export more than this, I suggest you use a date filter to limit each export to <1000 files, and adjust that filter until you have moved through all the records.

-

**Comment by LAURASOLEB** [comment]
Hi Matt,

I am conducting tests as you suggested to extract our chunks.

As you can see in the screenshot, I filtered by date to have less than 1,000 detections on my desktop.

***@***.***






















When I select the species to extract by right-clicking, the detections in the center disappear, and a message appears at the top right saying "No nocturnal Water Rail detections found using the custom list," and the download does not take place.

***@***.***

This does not happen without the date filter, and I have been able to download up to 4218 detections by going through the detection pages one by one. On each page, I could download 500 detections until page 10, which did not download anything (I have 16 pages).

Do you know what might be happening?

These analyses are for a scientific study related to my doctoral thesis, and for this reason, we have so many recordings to process.

Thank you very much.

Best regards,
Laura


De: Mattk70 ***@***.***>
Enviado el: lunes, 10 de junio de 2024 18:03
Para: Mattk70/Chirpity-Electron ***@***.***>
CC: Laura Solé ***@***.***>; Mention ***@***.***>
Asunto: Re: [Mattk70/Chirpity-Electron] Problem with audio clips export (Issue #131)


Hi @LAURASOLEB<https://github.com/LAURASOLEB>, updating the application will not affect any records saved to your archive. There is a limit of 1,000 files in the export. 1,000 audio files was more than I'd imagined someone would want to export in one go! If you want to export more than this, I suggest you use a date filter to limit each export to <1000 files, and adjust that filter until you have moved through all the records.

**Comment by LAURASOLEB** [comment]
Hi Matt,

I tested the date filter to obtain fewer than 1,000 detections for extraction.

Today, the detection list in the center does not disappear and allows the chunks to be extracted.

However, I have 943 detections in my desktop with the date filter, but it only extracts 692.

Could you help me please?

Thank you,
Laura

De: Laura Solé ***@***.***>
Enviado el: jueves, 13 de junio de 2024 16:47
Para: Mattk70/Chirpity-Electron ***@***.***>; Mattk70/Chirpity-Electron ***@***.***>
CC: Mention ***@***.***>
Asunto: RE: [Mattk70/Chirpity-Electron] Problem with audio clips export (Issue #131)

Hi Matt,

I am conducting tests as you suggested to extract our chunks.

As you can see in the screenshot, I filtered by date to have less than 1,000 detections on my desktop.

***@***.***






















When I select the species to extract by right-clicking, the detections in the center disappear, and a message appears at the top right saying "No nocturnal Water Rail detections found using the custom list," and the download does not take place.

***@***.***

This does not happen without the date filter, and I have been able to download up to 4218 detections by going through the detection pages one by one. On each page, I could download 500 detections until page 10, which did not download anything (I have 16 pages).

Do you know what might be happening?

These analyses are for a scientific study related to my doctoral thesis, and for this reason, we have so many recordings to process.

Thank you very much.

Best regards,
Laura


De: Mattk70 ***@***.******@***.***>>
Enviado el: lunes, 10 de junio de 2024 18:03
Para: Mattk70/Chirpity-Electron ***@***.******@***.***>>
CC: Laura Solé ***@***.******@***.***>>; Mention ***@***.******@***.***>>
Asunto: Re: [Mattk70/Chirpity-Electron] Problem with audio clips export (Issue #131)


Hi @LAURASOLEB<https://github.com/LAURASOLEB>, updating the application will not affect any records saved to your archive. There is a limit of 1,000 files in the export. 1,000 audio files was more than I'd imagined someone would want to export in one go! If you want to export more than this, I suggest you use a date filter to limit each export to <1000 files, and adjust that filter until you have moved through all the records.

**Comment by Mattk70** [comment]
Hi Laura, 

Your screenshots aren't appearing. I think this is because you are replying by email, could you come to the website and paste those screenshots in?

Nonetheless it sounds like you have 'nocmig mode' on, as you get the message "no **nocturnal** detections...". When it's on the icon is blue:
<img width="280" alt="image" src="https://github.com/Mattk70/Chirpity-Electron/assets/61826357/05dfce3d-39c4-41bc-8838-0af4594b0187">


If Chirpity determines a detection to be during daylight, the result on the right will have a blue background, if night time, the background is grey. There **might** be an issue with the total - reported in the summary table on the left - not accounting properly for the combination of filters you have applied. The total is affected by:

* The confidence threshold for detections
* Nocmig mode (it'll exclude daylight records)
* The date range applied
* The location - if you are filtering results for one place.

If it is giving a total that misses one of these, there will be pages in the pagination at the foot of the right hand table e.g. 10-16, which exceed the number of matching results. In that case, if you click page 16, you'd see no results. A quick check would be to read the total given in the summary table, then check the number of pages. There will be 500 results per page, so if you have 4218 results, there should be 9 pages in total, with the last page having 218 results.

One other thing, I know you are trying to export audio clips, but can you clarify what you mean by 'download'? I **think** you are talking about results being displayed in the right hand table.

**Comment by Mattk70** [comment]
Closing issue as stale
