### ISSUE TITLE
Round corners on the Mac icon

### ISSUE THREAD

**Issue by ltgustavsen** [Mattk70/Chirpity-Electron#133]
Just a very minor thing.  

The icon is nice, but the square icon is not very nice on a mac. It should be a round corner style. Look at the two markings in the screenshot. 

![Chirpity-icon](https://github.com/Mattk70/Chirpity-Electron/assets/15889329/58591330-285b-42a0-88b1-40e7c9b6bb9e)

**Comment by ltgustavsen** [comment]
I tried to modify the included icon. Hopefully it will work.

[icon.icns.zip](https://github.com/user-attachments/files/16401476/icon.icns.zip)

**Comment by Mattk70** [comment]
Hi - I've been able to "normalise" the Mac icon, but I need to decide if I am happy for the mac style icon to appear on the windows version, or develop logic to use the correct one when building for these different platforms.

**Comment by Mattk70** [comment]
Icon changed in https://github.com/Mattk70/Chirpity-Electron/releases/tag/v1.10.3
