### ISSUE TITLE
Timeline gets messed up

### ISSUE THREAD

**Issue by miboka** [Mattk70/Chirpity-Electron#134]
**First steps**

*Chirpity version: 1.10.2
*Operating system Mac: 14.5

**Describe the bug**
The timeline gets messed up. The timestamps from the file names are not properly interpreted.

**What steps cause the issue?**
I have a setup of 5 min recording and 25min pause that runs 24/7 (so 48 files per day). I load and process a week long of files for a weekly summary (336 files). While the timestamp for ca. 50% of the detections is interpreted correctly from the filename, a larger number of detections has a wrong timestamp, so they will not get sorted properly. The incorrect timestamps are also present in the csv export.  My  filenames are always as follows: Device_YYYYMMDD_HHMMSS.mp3 - see screenshot. I believe that my file naming is fairly standard, so I would think this as a bug while interpreting the filename.   Specifically, it appears that the last two YY digits (24) are incorrectly interpreted as the day of the recording.  It is a bit weird that some detections have correct timestamps while others do not.

**Expected behaviour**
A properly sorted timeline of detections

**Screenshots**

![Bildschirmfoto 2024-06-24 um 18 33 41](https://github.com/Mattk70/Chirpity-Electron/assets/112319417/d4d889f0-4236-47ad-87d1-b84d4bb9b58a)

**Additional context**

**Comment by Mattk70** [comment]
Chirpity doesn’t use the file’s _name_ to calculate when the file was recorded, it uses the last modified time in the file’s metadata. I suspect your issue is due to having modified the file in some way before analysis. To verify this, check the file info, and see if the modified time is as you expect according to the file name.

**Comment by miboka** [comment]
oops, I found the error. The file manager tampers with the last modified date (a 3rd party program). That is the culprit. Sorry, closed.
