### ISSUE TITLE
About Export Function—— add a feature to export the results as an Excel file

### ISSUE THREAD

**Issue by Pop1Ar** [Mattk70/Chirpity-Electron#135]
We use chirpity to identify the bird recordings and the results showed clearly. Thanks the author !
We are very interested to know that if there any ideas to add a feature in the future - to  output the recognition results in Excel format?
Thank you！

**Comment by Mattk70** [comment]
Hi, if you select File > Export Results to CSV, it will open just fine in Excel!

**Comment by Pop1Ar** [comment]
Thank you for your answer! ♥♥♥
