### ISSUE TITLE
Mac goes to sleep when analysing. 

### ISSUE THREAD

**Issue by ltgustavsen** [Mattk70/Chirpity-Electron#139]
On my Mac pro Chirpity stalls when analysing larger data set after a while when the mac goes black and idle. Sometimes it continues, but sometimes I have to start over.  It works great if I turn this behaviour off in the lock screen settings or even easer use the terminal command: 

caffeinate -i -t 7200 
That prevent the system from sleeping for two hours. Then everything works great.  Could something like this this be a program function? With a setting called “Prevent sleep/idle when analysing”

**Comment by Mattk70** [comment]
It is true that Chirpity doesn't recover well from computer sleep states, specifically when using one of the GPU backends for analysis. It is possible to prevent sleep, and earlier versions did this. However, I wasn't all that happy to override people's preferences for sleep (and power saving). I guess it could be an option you were able to enable if you chose to do so. I'll look into that.

**Comment by Mattk70** [comment]
I've added an option to prevent the computer going to sleep in https://github.com/Mattk70/Chirpity-Electron/releases/tag/v1.10.3
