### ISSUE TITLE
Jumping around timeline of long files

### ISSUE THREAD

**Issue by Akseli-Ilmanen** [Mattk70/Chirpity-Electron#145]
Hi! Appreciate the  help!

**Is your feature request related to a problem? Please describe.**
When looking at the spectrogram of long audio files (2-3h), it would be nice to have a feature with which I could navigate more efficiently between timestamps far apart.

**Describe the solution you'd like**
A timeline bar with which I can jump to different parts of the spectrogram. E.g. click on 2h15min and I jump to a 2min segment from there.

**Describe alternatives you've considered**
![image](https://github.com/user-attachments/assets/fb3ccdc2-23ef-4256-a4cb-81e9e03f0329)

What, I normally do is zoom out out to the maximum, click at the end of the time window, let the player pass the end, so it jumps to the next window. Then I repeat this step. This way, I can jump in 3min steps but is a bit tedious if I want to jump ahead 2h.

**Additional context**
NA

**Comment by Mattk70** [comment]
You can jump to any point in the file if you press Ctrl G and enter the position in the file you want to go to. Also PageDown/PageUp will move you ahead or back one screen at a time, no need to let the playhead move to the next screen each time.

**Comment by Akseli-Ilmanen** [comment]
Ahh that's great, thank you!!!
