### ISSUE TITLE
Not possibly to export audio clip

### ISSUE THREAD

**Issue by HansNorelius** [Mattk70/Chirpity-Electron#157]
It's not possible to export audio clips. 

After selection of a section, right-clicking on it and choose "Export audio clip" the save file dialog comes up.
It's not possible to choose file format, e.g. mp3. 
When entering a filename and press save no further dialog comes up, e.g. choosing quality. 
The dialog and windows closes and it lookes OK but nothing is saved.
![TR1](https://github.com/user-attachments/assets/84838f08-19b0-471b-a671-c2787a1e824a)

MvH Hasse

**Comment by Mattk70** [comment]
It is, but you need to save the file to the same drive as the one Chirpity is running on for now. The reason is documented in this issue: https://github.com/Mattk70/Chirpity-Electron/issues/156, it will be fixed in the next release.

**Comment by Mattk70** [comment]
Fixed in release 2.2.0
