### ISSUE TITLE
Volume Adjustment and Normalization not working (with m4a and WAV files)

### ISSUE THREAD

**Issue by Vollpflock** [Mattk70/Chirpity-Electron#162]
**First steps**
Let us know a little about your setup. Ideally, provide a screenshot of the window which appears when you choose  Help > Diagnostics in the menu will often be useful - as it captures all the relevant  system and settings information. Minimally, please let us know:
*Chirpity version:*
*Operating system (PC/Mac):*

![Screenshot 2024-11-01 at 19 36 17](https://github.com/user-attachments/assets/e96670d0-6c44-4963-b6c7-e2bf54c14754)

**Describe the bug**
Volume adjustment and normalization not working with m4a files.

**What steps cause the issue?**
Describe the steps followed to reproduce the problem, for example:
1. Launch Chirpity
2. Volume adjustment to +50db AND/OR normalization turned on
3. Open m4a file or WAV file
4. Nothing happens (it's not louder)

**Expected behaviour**
It should be louder

**Additional context**
Haven't tried with other file formats

**Comment by Mattk70** [comment]
Fixed in v2.2.4 ( and you can save clips with volume adjustment) Normalise works the way it always has.

**Comment by Vollpflock** [comment]
This is working great, thank you! Love that volume adjustment gets applied on export as well
