### ISSUE TITLE
Error message: "The database has not finished Ioading. The check for the presence of the file in the archive has been skipped"

### ISSUE THREAD

**Issue by davejbur** [Mattk70/Chirpity-Electron#166]
Similar to closed issue #80. I've uninstalled & reinstalled, but when I try to open a file I get the above error message.

Chirpity version 2.3.2
WIndows 11 Home 23H2 version 22631.4317, "Windows Feature Experience Pack" 1000.22700.1041.0
![image](https://github.com/user-attachments/assets/8d77159a-854a-4ae5-b92f-19ad25109be0)

I've no idea whether I'm using AVX or not...! How do I check?

Thanks!

**Comment by Mattk70** [comment]
Hi @davejbur, I've literally *just* discovered that new users have been unable to install the application due to a bug in the code used to set the version. 2.3.3 was released about 10 minutes ago, which should fix this.

**Comment by davejbur** [comment]
Hi Matt, that works fine now, many thanks!
