### ISSUE TITLE
The list of bird sound results is in English

### ISSUE THREAD

**Issue by sebvdn** [Mattk70/Chirpity-Electron#177]
The list of bird sound results is in English, although the entire interface is in French.
![Capture d'écran 2024-12-29 080558](https://github.com/user-attachments/assets/6c5d6a08-18f7-4935-9985-a59b85f78133)

**Comment by Mattk70** [comment]
Hi @sebvdn, 
The labels for each model are independent, so you need to set the language for both BirdNET and the Nocmig model separately.
