### ISSUE TITLE
Feature requests (first look)

### ISSUE THREAD

**Issue by Vollpflock** [Mattk70/Chirpity-Electron#21]
As already mentioned, it’s a wonderful piece of software and it’s obvious that you put a lot of thought into it. I've had a quick look at the Apple Silicon version, and while I'm still familiarizing myself with it, I already have a few questions and suggestions.

Questions and Feature Requests (edited: 29.01.2024):

1. Can experimental filters be applied post-analysis for better results without going into settings every time? I mean if I turn off “Experimental audio filters applied” on the right before analysis and apply them afterwards, will the analysis be filter-free? I'm curious because I've read that applying noise reduction post-analysis generally yields better results.
2. An option to apply the experimental features (except context mode) only after-analysis? I really appreciate these for better sound.
3. Option to create a custom species list.
4. Support for species lists in different languages.
5. Custom file naming or a similar format like birdnet-pi (f.e. “_By_Date_2024-01-04_Gadwall-93-2024-01-04-birdnet-23_05_42”)
6. Amplification feature in experimental settings and maybe low-pass filter (because crickets)
7. What’s the file size limit? I tried it with a 2.5 GB file and it worked, however, 15 GB file doesn’t work.
8. Maybe an option to filter results after analysis? F.e. nocturnal and dirunal mode after analysis (before and after sunset/sunrise)? Or to search for certain species?
9. How can I retrieve archived calls? I'm sure I'm doing something wrong, but it's not working on my end.
10. Scrolling through the spectrogram or a shortcut to get to the next frame or so.
11. Cycling through recordings (Skip to the next detection) by clicking on the species multiple times (like MerlinID app does).
12. Sorting all columns (ascending and descending sort).

**Comment by Mattk70** [comment]
Hi @Vollpflock - thanks again for the feedback, I'm stoked you're so engaged!

Many of these features alreeady exist. You can bone up on all the keyboard shortcuts in the help menu item called... Keyboard shortcuts.

These are the features you've talked about that are present:

8. Maybe an option to filter results after analysis? F.e. nocturnal and dirunal mode after analysis (before and after sunset/sunrise)? Or to search for certain species?

Nocmig mode and confidence threshold can be amended after analysis - select/click the appropriate button on the filter panel. To filter specific species - click that species' name in the summary. Click a filtered species again to 'unfilter' .

9. How can I retrieve archived calls? I'm sure I'm doing something wrong, but it's not working on my end.

First save results to an archive: Records > Save to Archive (or control S). Retrieve results: Records > Explore archive

10. Scrolling through the spectrogram or a shortcut to get to the next frame or so.

Various keyboard shortcuts control the audio playback and spectrogram position. PageUp and PageDown allows you to page through the spectrogram, one screen width at a time. On a Mac laptop, that's function key - arrow Up/Down

11. Cycling through recordings (Skip to the next detection) by clicking on the species multiple times (like MerlinID app does).

'Tab' is your friend. Shift tab goes backwards.

12. Sorting all columns (ascending and descending sort).

To sort by time click the time / position heading in the results table. To sort by species, click species. These are the only sortable columns for now.


To the other points:
1. I'm not sure I understand. If these features are enabled (yellow icon in filter panel) *before* analysis, they are applied to the audio sent to the model. If they are applied (or disabled) *after* analysis, the detections are unaffected.
2. I think I've answered this above
3. I get this is a feature in BirdNET, but I'm not convinced this is the best approach. What *exactly* are you looking to acheive?
4. If there's sufficient demand, I can look to bring in the translated labels from BirdNET-Analyzer for the BirdNET species list. The list in the native model uses a different Taxonomy, so would need translating separately. 
5. Again, a little more context would be helpful here - I'm not sure entirely what you trying to achieve (although I kind of do, if you want files to fit into your own naming converntions)
6. I am not sure what an amplificaiton filter means. Both models normalise any audio they receive (this effectively expands the dynamic range of the spectrograms, and helps with their performance) The spectrogram in the UI also normalises the audio - but what you hear is untampered with, unless you have an audio filter applied. Low pass filter - should be striaghtforward, I'll look into it for the next version.
7. Finally, I have no idea what the size limit is and I don't have any 15GB files. Off the top of my head, I'm not sure there would be one - if the OS can handle it, Chirpity should have no problem. When you say 'doesn't work', what was the issue?

If you'd like to expand on those issues I'm not clear about, it'd be great if you could use the issue or new feature template - it really does help capture what I need to know to solve the problems.

**Comment by Vollpflock** [comment]
Apologies for not digging deeper on my own.

I've just discovered the Mac shortcuts, which is fantastic.

I've created an issue/feature request for each query. Feel free to close them, as some aren't important at all.
