### ISSUE TITLE
Experimental features post-analysis

### ISSUE THREAD

**Issue by Vollpflock** [Mattk70/Chirpity-Electron#25]
Initial questions: 1. Can experimental filters be applied post-analysis for better results without going into settings every time? I mean if I turn off “Experimental audio filters applied” on the right before analysis and apply them afterwards, will the analysis be filter-free? I'm curious because I've read that applying noise reduction post-analysis generally yields better results.

2. An option to apply the experimental features (except context mode) only after-analysis? I really appreciate these for better sound.

Your answer: 
1. I'm not sure I understand. If these features are enabled (yellow icon in filter panel) before analysis, they are applied to the audio sent to the model. If they are applied (or disabled) after analysis, the detections are unaffected.
2. I think I've answered this above

More detailed:
Are the experimental features applied before or after analysis in the following example? I activated them in settings but only on the left side, not the right. The first screenshot shows the state during analysis, and the second shows it post-analysis
![Screenshot 2024-01-29 at 17 14 14](https://github.com/Mattk70/Chirpity-Electron/assets/26574621/4cbe0b7a-1db6-4488-99fe-eb0ff07faac7)
![Screenshot 2024-01-29 at 17 14 47-min](https://github.com/Mattk70/Chirpity-Electron/assets/26574621/fec1522d-5bc5-4acf-8fcc-320a8b1db82b)

**Comment by Mattk70** [comment]
In your first screen shot, it shows the filters are disabled. If you run an analysis in this state, the audio passed to the model for prediction is unaffected by the settings you have in the settings panel. If, after the analysis, you enable the filters, it will only affect the audio you hear, it will not change the predictions.

**Comment by Vollpflock** [comment]
Awesome, thank you
