### ISSUE TITLE
Support for species lists in different languages. 

### ISSUE THREAD

**Issue by Vollpflock** [Mattk70/Chirpity-Electron#27]
Initial question: 4. Support for species lists in different languages. 

 Your answer:
If there's sufficient demand, I can look to bring in the translated labels from BirdNET-Analyzer for the BirdNET species list. The list in the native model uses a different Taxonomy, so would need translating separately.

More detailed:
 That sounds daunting. I was inspired by Frank's post on BirdNET-Analyzer, assuming it would be similar here (https://github.com/kahst/BirdNET-Analyzer/issues/1). The process should be straightforward and automated, of course.  

For translation, perhaps DeepL (https://www.deepl.com/en/translator) could be useful? It's accurate for bird species names between German, English, and French. I haven't tried other languages yet. My experience with species translation using ChatGPT (GPT-4 128k) wasn't great. However, you're in the UK and might use Claude 2.1, which could be more effective – I haven't had the chance to test it.

**Comment by Mattk70** [comment]
I'm on the case :) I have translations working,  more or less. I just need to make it work a little better. Ideally, you'd change a language dropdown and everything you got would would turn Japanese or whatever. Watch this space.

**Comment by Vollpflock** [comment]
I just went through the code. It looks very promising – great work!

**Comment by Mattk70** [comment]
So, this is now a feature in 0.12.0. I managed to figure out a way to apply the language labels to the native model too. In my exploration, I also found a way to apply UK English names to the BirdNET model. No more reports of Brant (Brent Goose) or Green-winged Teal (Eurasian Teal). The Eurasian Thick-knee is now a Stone-curlew. Marvellous.
