### ISSUE TITLE
File size limit?

### ISSUE THREAD

**Issue by Vollpflock** [Mattk70/Chirpity-Electron#29]
Initial question: 7. What’s the file size limit? I tried it with a 2.5 GB file and it worked, however, 15 GB file doesn’t work.

Your Answer: 

Finally, I have no idea what the size limit is and I don't have any 15GB files. Off the top of my head, I'm not sure there would be one - if the OS can handle it, Chirpity should have no problem - unless that is, it was a compressed file. What was the file type? Also, when you say 'doesn't work', what was the issue?

More detailed:
.wav files. The import doesn't work – it simply does nothing. Activity Monitor shows almost no CPU usage. The screenshot below illustrates this.

It's just one file, though a lengthy one – don't ask why I recorded for 10 days straight. I need to split it, but it's too large for tools like sox. I admit, recording for 10 days straight wan’t the brightest idea. 

Feel free to close this issue, it's not a major concern at all.

I really need to test how the system handles many small files. It would be incredible to analyze a week's worth of recordings in one go.

![Screenshot 2024-01-29 at 19 04 38](https://github.com/Mattk70/Chirpity-Electron/assets/26574621/8281253e-e8af-40a1-8f11-2884cac52435)
![Screenshot 2024-01-29 at 22 18 34](https://github.com/Mattk70/Chirpity-Electron/assets/26574621/3dc46de8-d20e-4d99-83e8-591f798eda5a)

**Comment by Mattk70** [comment]
Yeah, OK that's not al lot to go on. You could enable debug mode to get me some log messages. It's at the bottom of the settings menu and you'll need to relaunch the application for it to take effect. In debug mode two windows will open. Go to the 'sources' tab of each window and look for the Errors in red...like here:
![Screenshot from 2024-01-29 22-37-24](https://github.com/Mattk70/Chirpity-Electron/assets/61826357/3a211ed5-2905-4955-8667-92843c8a81a3)
. 

Click on the errors line and paste them here or screenshot, it may help me work out what's going on. If there aren't any errors, it may just be too big a file, and the OS isn't getting it to the app. If anything can split it, ffmpeg would be my goto.

As for the number of files, it's good for at least 20,000. Much beyond that, Windows/Linux  struggles to handle things. Those figures might be dependent on system RAM. Also if you notice it starts slowing down after processing a few days worth of audio (i.e. a batch of 100 hours or so) I know why that is. The database starts to lag when updating the summary after every batch of predictions. The solution is to reduce the summary update frequency, but I haven't got around to that. Give it a go, let me know?

**Comment by Vollpflock** [comment]
`Yeah, OK that's not al lot to go on. You could enable debug mode to get me some log messages. It's at the bottom of the settings menu and you'll need to relaunch the application for it to take effect. In debug mode two windows will open. Go to the 'sources' tab of each window and look for the Errors in red...like here:`

I should have mentioned, I already tried debug mode, but it didn't reveal anything useful. Here's a screenshot taken after opening the file in debug mode.
![Screenshot 2024-01-30 at 00 12 00](https://github.com/Mattk70/Chirpity-Electron/assets/26574621/e982829f-876f-4fe0-bed3-2bf0519d37c0)

`As for the number of files, it's good for at least 20,000. Much beyond that, Windows/Linux struggles to handle things. Those figures might be dependent on system RAM. Also if you notice it starts slowing down after processing a few days worth of audio (i.e. a batch of 100 hours or so) I know why that is. The database starts to lag when updating the summary after every batch of predictions. The solution is to reduce the summary update frequency, but I haven't got around to that. Give it a go, let me know?`

I tried it with 100 and 300 hours of audio and it appears the issue was minimal and mainly related to the kernel_task consuming CPU resources, though more tests will be needed. I plan to try processing 1000 hours of audio in the future.

I'll close this issue for now, as it doesn't seem critical. Realistically, audio files shouldn't be excessively long anyway.
