### ISSUE TITLE
Species Selection Issue in 'Edit Record' When Using Non-Default Language

### ISSUE THREAD

**Issue by Vollpflock** [Mattk70/Chirpity-Electron#35]
**Describe the bug**
When using non-default language and I click 'edit record,' it doesn't automatically select the species. Plus, it won't get translated.

**To Reproduce**
See SC.

**Expected behavior**

**Screenshots**
![Screenshot 2024-02-01 at 15 22 13](https://github.com/Mattk70/Chirpity-Electron/assets/26574621/21d128ba-0562-4e96-94e5-9075ac918af5)
![Screenshot 2024-02-01 at 15 22 27](https://github.com/Mattk70/Chirpity-Electron/assets/26574621/e71da913-6251-497d-be7e-6106de4a2104)
![Screenshot 2024-02-01 at 15 22 44](https://github.com/Mattk70/Chirpity-Electron/assets/26574621/1f377e67-2a95-45fa-9958-eb458f2afaea)

**Additional context**
Minor issue

**Comment by Mattk70** [comment]
Hi @Vollpflock I've puslished a pre-release for the fix. Have a look, see if it works for you?

https://github.com/Mattk70/Chirpity-Electron/releases/tag/v0.12.1

**Comment by Vollpflock** [comment]
Works like a charm. Btw, regarding the archive function: I need to do some digging and will be back.
