### ISSUE TITLE
Apply experimental audio filters on export

### ISSUE THREAD

**Issue by Vollpflock** [Mattk70/Chirpity-Electron#36]
**Is your feature request related to a problem? Please describe.**
High noise and poor audio quality. 

**Describe the solution you'd like**
Automatically apply experimental audio filters to audio clip during export when enabled.

**Describe alternatives you've considered**
Manually applying denoise filters for every file in Audacity after export.

**Comment by Mattk70** [comment]
I have looked into this a while back. I have this comment in my code to remind me:

```
// This code doesn't work: error opening filters

 if (STATE.filters.active){
     ffmpgCommand = ffmpgCommand.audioFilters(
          {
              filter: 'lowshelf',
              options: "gain=${STATE.filters.lowShelfAttenuation}:f=${STATE.filters.lowShelfFrequency}"
          },
          {
              filter: 'highpass',
              options: "f=${STATE.filters.highPassFrequency}:poles=1"
          } 
      )
  }
```
It *may* be that the static FFMPEG binary I use was not complied with these filters. I also remember running into issues building a custom static Windows binary tuned for Chirpity from source. I was trying to do this as the FFMPEG features in need can be packaged into a binary of about 2-3MB (the build did compile on UNIX) whereas the binary I have is about 55MB - it contains heaps of video functionality I don't need.

**Comment by Mattk70** [comment]
I updated the FFmpeg binary in release [v1.1.0](https://github.com/Mattk70/Chirpity-Electron/releases/tag/v1.1.0) and this has fixed the issue. Now Low Shelf, High Pass and Gain will, if enabled in the UI, be reflected in exported files.
