### ISSUE TITLE
Edit Record not working if in user-defined language

### ISSUE THREAD

**Issue by DD4WH** [Mattk70/Chirpity-Electron#37]
**Describe the bug**
* Chirpity 0.12.1
* BirdNET model
* using German as language for bird species
* Right-click -> Edit Record does not show the species that BirdNET classified, but "All Species"
* if I choose the correct species, Chirpity does not show that species as confirmed on the Left side list

**Comment by Mattk70** [comment]
No problem. 0.12.1 is a [pre-release](https://github.com/Mattk70/Chirpity-Electron/releases/tag/v0.12.1). I'm working on adding the "week" option to the location filter. When I have done this, I'll push out 0.13.0. At least, that's the plan.

**Comment by Vollpflock** [comment]
This seems to be an issue again under v1.6.9
