### ISSUE TITLE
Issue with Accessing Saved Results

### ISSUE THREAD

**Issue by Vollpflock** [Mattk70/Chirpity-Electron#51]
**Describe the bug**
After exiting Chirpity, I reloaded all the files from my external drive. They showed up in the system, and the 'Retrieve Results' option was highlighted in dark black, indicating it was active. However, clicking on it had no effect. It appears that the file is properly saved in the library, but I still can't access the results."

**Expected behavior**
It should load retrieve results.

**Screenshots**
![Screenshot 2024-02-17 at 08 53 23](https://github.com/Mattk70/Chirpity-Electron/assets/26574621/1ebcb786-c467-4030-8b46-b464b5eb9e7e)
![Screenshot 2024-02-17 at 09 00 00](https://github.com/Mattk70/Chirpity-Electron/assets/26574621/f8c54941-e84e-4139-b363-730ef73d8403)

**Additional context**
Again, this happened with the 820 x 1 hour long files. 

Version 1.1.0
Mac

**Comment by Mattk70** [comment]
If you select retrieve results twice, does it work the second time?

**Comment by Vollpflock** [comment]
nah dog, it's too late, i just started reanalyzing all of them. that actually seems to work though
