### ISSUE TITLE
Error after editing a record

### ISSUE THREAD

**Issue by Vollpflock** [Mattk70/Chirpity-Electron#53]
**Describe the bug**
Error after editing a record.

**To Reproduce**
1. In archive, apply a date filter.
2. Edit a record.

**Expected behavior**
Should not get an error code.

**Screenshots**
![Screenshot 2024-02-24 at 08 13 14](https://github.com/Mattk70/Chirpity-Electron/assets/26574621/033f33ca-63ad-415c-b4d4-00d77d110f1a)

![Screenshot 2024-02-24 at 08 13 27](https://github.com/Mattk70/Chirpity-Electron/assets/26574621/782bad41-482f-42c5-9552-4e6f968d6272)
![Screenshot 2024-02-24 at 08 13 36](https://github.com/Mattk70/Chirpity-Electron/assets/26574621/bb26acf4-e463-4611-9e7d-307838ef7919)
![Screenshot 2024-02-24 at 08 13 51](https://github.com/Mattk70/Chirpity-Electron/assets/26574621/d3544b9a-b905-42c0-ac14-c471c8a122b9)

**Additional context**

Chirpity 1.2
MacOS

**Comment by Mattk70** [comment]
This will be fixed in 1.3. Also, the button to clear the date filter is missing, this is fixed too.
