### ISSUE TITLE
Amending location not working

### ISSUE THREAD

**Issue by Vollpflock** [Mattk70/Chirpity-Electron#55]
**### 1st issue I encountered:**

**Describe the bug**
Location not showing up in archive.

**To Reproduce**
1. Open files
2. Amend location to all files
3. Analyze them
4. Save to archive
5. Go to archive
6. Location doesn't show up, only "All locations"

**Expected behavior**
The location should show up in the archive.

**Screenshots**
![Screenshot 2024-02-25 at 07 10 39](https://github.com/Mattk70/Chirpity-Electron/assets/26574621/5339d586-8dff-46a4-9d02-c7b7cba73ef6)

**Additional context**
There's no error code. Sometimes it workes - maybe only with a few files? Not sure. 

**### 2nd issue I encountered:**

**Describe the bug**
Location showing up in archive but non responsive when selecting it (doesn’t do anything).

**To Reproduce**
1. Go to archive
2. Select the location

**Expected behavior**
When selecting the location in the archive, it should only show recordings taken from that location.

**Screenshots**
![Screenshot 2024-02-25 at 07 16 32](https://github.com/Mattk70/Chirpity-Electron/assets/26574621/d87d0555-adda-49c2-875d-1663182e9525)

**Additional context**
There's no error code.
Plus, when saving a new location it (sometimes?) overrides the other locations.

**Comment by Mattk70** [comment]
Hi - thanks for this. It looks like I don't copy across locations set in memory when you save to the archive. Easy to fix. This should also prevent locations being overwritten. The second issue of not filtering is separate, but also a simple fix.  I'll release a patch.

**Comment by Mattk70** [comment]
Patch 1.3.1 released

**Comment by Vollpflock** [comment]
fantastic
