### ISSUE TITLE
Export Results to CSV with Latitude and Longitude 

### ISSUE THREAD

**Issue by Vollpflock** [Mattk70/Chirpity-Electron#57]
**Is your feature request related to a problem? Please describe.**
No, I just want an efficient workflow for reporting birds to ebird/trekstellen etc.

**Describe the solution you'd like**
Two additional columns in the CSV file, one for Latitude and one for Longitude.

**Describe alternatives you've considered**
none

**Additional context**
no

**Comment by Mattk70** [comment]
Hey - yes, this will be a feature in 1.4.0 - coming soon.

**Comment by Mattk70** [comment]
Added feature in #60

**Comment by Mattk70** [comment]
You should find the export eBird Record feature useful in 1.6.0. It's a first stab at this, but it should save heaps of time preparing an import for the site.

**Comment by Vollpflock** [comment]
Thank you, I already have my own script for ornitho. However, I tried this feature and it doesn't seem to work. 

Steps:
2. Explore Archive
3. Set date
4. Set Location
5. Export ebird record file

-nothing happens and no error code. 
![Screenshot 2024-03-13 at 16 46 57](https://github.com/Mattk70/Chirpity-Electron/assets/26574621/20549402-79af-4f1c-b174-f6d806a1ae3e)
![Screenshot 2024-03-13 at 16 47 27](https://github.com/Mattk70/Chirpity-Electron/assets/26574621/34f38b70-9127-4932-a9ed-b9b8862b7133)

**Comment by Mattk70** [comment]
Interesting. Doing that works for me. Let me try it on the Mac...

**Comment by Mattk70** [comment]
And it works on my Mac as well

**Comment by Vollpflock** [comment]
Well, if it's just me, it doesn't matter. I don't intend to use it anyway.
