### ISSUE TITLE
Multiple windows support

### ISSUE THREAD

**Issue by Vollpflock** [Mattk70/Chirpity-Electron#58]
This is very minor, but I thought I’d ask.

### Reason 1
**Is your feature request related to a problem? Please describe.**
I maintain an archive of calls for reference purposes, allowing me to compare them with the recording. However, the issue is that I lack spectrograms for comparison.

**Describe the solution you'd like**
Multiple windows support: Uploading all these reference calls into the Chirpity archive and assigning a specific location. If Chirpity supported multiple windows, I could effortlessly compare them using spectrograms by opening the reference archive in another window.

**Describe alternatives you've considered**
Xeno-Canto is another potential resource, but it's not as efficient for quickly finding the specific calls I'm looking for.

**Additional context**
no

### Reason 2
**Is your feature request related to a problem? Please describe.**
If I have recordings captured simultaneously at various locations, I can't analyze them all at once (for example, in a single night) but need to analyze each batch separately.

**Describe the solution you'd like**
Multiple windows support: Support for multiple windows could potentially allow me to open several windows at once, enabling overnight analysis in a single batch.

**Describe alternatives you've considered**
Analyzing batch by batch.

**Additional context**
no

**Comment by Mattk70** [comment]
Hmm. On Windows, you *can* open multiple application windows. But not, it seems on a Mac. I haven't tested how the application works when you have multiple instances open. They will share a lot of the same resources - notably the database and config file. This might lead to unexpected behaviour, but the sqlite database _seems_ to manage the locks it needs quite well. I don't know how to enable multiple instances on a Mac, but I'll look into it.

**Comment by Mattk70** [comment]
Meanwhile, you can check the calls on XC, and if you set up your XC account "correctly", the default view will have spectrograms for the calls.

**Comment by Mattk70** [comment]
Just to be clear about how you hope to achieve your reference archive. Are you thinking that you will assign a "special location" for reference calls, and then - if you were able to open 2 windows, set up the refeence window to filter results to that location while using the other window to run analyses?

**Comment by Vollpflock** [comment]
Exactly - or a specific date.

**Comment by Mattk70** [comment]
OK. I looked into it. Here's how. 

Launch Chirpity. Open the teminal app, then type the magic:

```
open -n /Applications/chirpity.app
```

This will launch a new Chirpity window.

**Comment by Vollpflock** [comment]
Thank you very much
