### ISSUE TITLE
Goes blank after creating a record from archive

### ISSUE THREAD

**Issue by Vollpflock** [Mattk70/Chirpity-Electron#64]
**Describe the bug**
You probably already got the error over analytics. It goes blank after creating a record.

**To Reproduce**
1. Go to archive
2. Select a location
3. Create record from a detection
4. It goes blank.

**Expected behavior**
Should not go blank. 

**Screenshots**
![Screenshot 2024-03-08 at 22 48 27](https://github.com/Mattk70/Chirpity-Electron/assets/26574621/b21046c6-3373-4aa3-9cd3-763ca2c07d52)
![Screenshot 2024-03-08 at 22 48 36](https://github.com/Mattk70/Chirpity-Electron/assets/26574621/7c0d5bda-31c9-449e-94d9-f330b7b62e73)
![Screenshot 2024-03-08 at 22 48 45](https://github.com/Mattk70/Chirpity-Electron/assets/26574621/2364693e-28ce-4c3a-bdd7-679063ee0dcf)

![Screenshot 2024-03-08 at 22 50 54](https://github.com/Mattk70/Chirpity-Electron/assets/26574621/6736571a-0ac8-4efe-a55b-6d688ed6856f)

**Additional context**
Mac, v1.5.1

**Comment by Mattk70** [comment]
Thanks @Vollpflock - this is an excellent bug report. I've reproduced the error and found the offending code. So, I have a fix.
