### ISSUE TITLE
Spectrogram is frozen

### ISSUE THREAD

**Issue by FlorianH27** [Mattk70/Chirpity-Electron#65]
Since the new update to version 1.5.1, I have been experiencing a bug where the Spectrogram is frozen. If I click on a detection after the analysis, the detection is not displayed in the spectrogram. The spectrogram remains in the view for the entire length of the whole file. I don't know whether Chirpity is simply running very slow on my device or whether the error also occurs on other devices.

**Comment by Mattk70** [comment]
Hi @FlorianH27,

I'm sorry to hear you're having issues. I can see from my logs there is one individual that's got a very troubled Chirpity, it must be you! I'm going to suggest you uninstall the application (using add / remove programs in Windows) and re-install it.

Uninstalling will clear all data, including the archive database. If you want to save your archive, here's how:

1. Hold down the windows key and hit R, it'll bring up the Run window. 
2. Type %APPDATA% in there and hit return.
3. Find and go into the "chirpity" folder.
4. You should see one or two files named "archive" one is archive409.sqlite and the other is archive6523.sqlite. Depending on your settings, you may not see the ".sqlite" extension.
5. Copy these files out of the folder - put them somewhere safe. You'll copy them back when you reinstall the app.

Once you've done that, uninstall the app using add/remove programs. Then install a fresh copy.

**BEFORE** you copy the database files back, open the newly installed app. See if it works. If it does, close the app and move the archive files back into the folder they came from (repeat steps 1-4 and overwrite the archive files if prompted). Open the app again and let me know how it goes?

I hope that works!

**Comment by FlorianH27** [comment]
Thank you for your answer! It works much better now. It's still a bit slow, but that's probably just due to my device.
