### ISSUE TITLE
Problem exporting all audio clips

### ISSUE THREAD

**Issue by Maguinya** [Mattk70/Chirpity-Electron#67]
I have tried to use the option to export audio clips to be able to export all the detections chirpity made for multiple files, however, it seems Chirpity doesn't allow for this option. Or at least I receive a notification that says "undefined". Not sure if it's just a problem I have? I also wanted to take the opportunity to ask if would be possible to add the file name on the name of the exported audio clip? Or something similar to BirdNET. The time stamp that it currently has is not very easy to understand (or infer to when looking at the original audio file) Thanks!

**Comment by Vollpflock** [comment]
Just to understand: What exactly are you trying to do, exporting audio clips or exporting all detections in a CSV file? 
As of my knowledge, changing the file name format is not possible at the moment.

**Comment by Maguinya** [comment]
I am trying to export the audio clips, thanks!

**Comment by Mattk70** [comment]
HI @Maguinya, thanks for letting me know.

I have to confess I am a little confused as well.

>  have tried to use the option to export audio clips to be able to export all the detections chirpity made for multiple files

Do you mean you are trying to export audio clips, one species at a time? There isn't a way to export all detections for all species with a single click.

When I try this (right click on a species in the summary and select export audio clips), it works for me. Perhaps you could post a screenshot of your issue?

Regarding file names, what does BirdNET do? Also, if you want to find the section of the original file that the clip came from, this should be straightforward. When you are exploring your saved records, filter by the clip species and scroll to the date/time in question. You would just need to make sure you are using the time-of-day mode to show the date/time in results. Ctrl-T (Command-T on a Mac) toggles this on or off.

**Comment by Maguinya** [comment]
Hi @Mattk70, thank you for your response. 

Yes I was trying to export all audio clips at once (but I see now that that isn't an option), I was trying to do this from the Records tab in the left hand corner (without selecting a specific species). The option you mention of exporting all audio clips of one species also gives me the same issue though, "undefined" notice in the right hand corner. 
![Screenshot_chirpity_LI](https://github.com/Mattk70/Chirpity-Electron/assets/163280946/cea52edf-bfad-499d-a17d-cd60194598f7)

In regards to the file names, BirdNET names the exported audio files (as they call segments) with the confidence score and the original file name, for example: 0.509_21_GR34_20230927_050700 . But now I see I didn't have the date time mode on in Chirpity, thanks!

**Comment by Mattk70** [comment]
Got it. That is a bug. The message should read: "Filter results by species to export audio files"

**Comment by Mattk70** [comment]
Fixed in 1.6.0

**Comment by Maguinya** [comment]
Thank you!!
