### ISSUE TITLE
Cmd + Q does not work with all applications

### ISSUE THREAD

**Issue by Vollpflock** [Mattk70/Chirpity-Electron#75]
**Describe the bug**
Cmd + W (closing window) is not working with Chirpity on Mac, which is fine. However, when Chirpity is installed, Cmd + Q (quitting applications) doesn’t seem to work on all applications except Chirpity. 

**Additional context**
Mac Version

**Comment by Mattk70** [comment]
Yes, it seems when you register a globabl shortcut in Electron, it captures the command - preventing normal behaviour for other apps! This is only when you have Chirpity open, if it's not running, Commnad+Q works normally for other apps. 

I'll fix it in the upcoming release.

**Comment by Mattk70** [comment]
Fixed in https://github.com/Mattk70/Chirpity-Electron/discussions/77
