### ISSUE TITLE
More precise coordinates?

### ISSUE THREAD

**Issue by Vollpflock** [Mattk70/Chirpity-Electron#79]
**Is your feature request related to a problem? Please describe.**
I have recording stations which are located quite closely. Now, there are only 2 two decimal places for latitude and longitude, which makes it impossible for me to distinguish the recording stations.

**Describe the solution you'd like**
More decimal places.

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by Mattk70** [comment]
OK. I'll make it 4 decimal places.

**Comment by Mattk70** [comment]
This has been added to 1.6.3
