### ISSUE TITLE
Some WAV Files work, others don't

### ISSUE THREAD

**Issue by CountryTec** [Mattk70/Chirpity-Electron#85]
**Describe the bug**
Some of my wav files taken by Zoom F6 with 96kHz 32bit work, others don't. Did not find any pattern. Error message says invalid wav header.

**To Reproduce**
1. Load the file
2. Start Analysis
3. see error message

**Expected behavior**
do the analysis as for the other files

**Screenshots**
If applicable, add screenshots to help explain your problem. The Help > Diagnostics window will often be useful - as it captures important system and settings information.

<img width="345" alt="Bildschirmfoto 2024-03-29 um 19 52 59" src="https://github.com/Mattk70/Chirpity-Electron/assets/165419572/81e9c21c-63da-4a6e-8661-9261596441e4">

**Additional context**
Am running it on a MacBook Pro M3 MAX with 64GB of Ram. The software is incredibly fast and using almost all CPU power available.

**Comment by Mattk70** [comment]
Hi @CountryTec, before today’s 1.6.6 release, the app didn’t recognise wavs with an uppercase extension. If that’s not the issue, you’ll need to share an example wav that produces the error - otherwise I’ve nothing to go on. You can do that here if you first zip it.

**Comment by CountryTec** [comment]
Thanks Matt for coming back that fast. 
Am working on 1.6.6 version already and dit try with upper- and lowercase extensions. Still having same issues. 
Did put some files on the dropbox for you to have a look on. There are 32bit 96kHz and 24bit 44.1kHz wav’s.
Best,
Wilfried

https://www.dropbox.com/scl/fo/x33nqw4zbktd40hl72b1f/h?rlkey=c17vcj7fvw69op629rtlfu4d8&dl=0￼
Chirpity
dropbox.com

**Comment by Mattk70** [comment]
Thanks for sharing the files.

The ones which don't work are more exotic wav file formats. They contain the BEXT and iXML metadata extensions. The library I use to parse the wav headers doesn't understand these and can't find where the audio starts.

I'll see if I can get Chirpity to parse them by routing the files through Ffmpeg.

**Comment by CountryTec** [comment]
Thanks Matt, that was a good hint. As a workaround am processing the files using Sound Studio (import and simply export) looks like the "strange" metadata is removed. With this workaround Chirpity can process the files with no error.

**Comment by Mattk70** [comment]
So - after a bit more investigation, I have found the problem and solution. In order to extract the wave header, I was reading the first 4k of the file. It turns out with the additional metadata, the header for these files is longer than that, in fact it appears to be 128k. Now I read this amount in, the header is parsed correctly.

**Comment by CountryTec** [comment]
V1.6.8 works perfectly fine with my files coming out of the Zoom F6. Amazing service. Thanks Matt!

**Comment by Mattk70** [comment]
You're welcome - I'm glad the fix was so simple, even if it took a fair bit of head-scratching to figure out what the issue was!!

**Comment by CountryTec** [comment]
in case you want to add some performance information on M3 MAX just share the benchmark files and i will return the time my monster needs to analyze them. Best, CountryTec

**Comment by Mattk70** [comment]
Thanks @CountryTec, it'd be interesting to see the progress between the M2 and M3. I don't have access to the file at the moment, as I'm away from home. It was essentially a 1GB mono wav file with a 48k sample rate.

The best performance I've seen is using the WebGL backand on a machine with an NVIDIA 3090. This can get to speeds around  1200x - so it processes an hour of audio every 3 seconds! At these speeds, I suspect it's not prediction that's the bottleneck, it's file IO and resampling.

**Comment by CountryTec** [comment]
Gave it a try. With 32bit mono of one hour it took 16 Seconds to get it done. With 32bit of around 1GB data (almost two hours) it took 24 seconds. Maybe once your are back home we try again with the benchmark-files. ;)

**Comment by CountryTec** [comment]
Dear Matt, last two night recordings did fail again with the "invalid header" information. 
Have stored a working and a non working file on the dropbox.
My workaround is still "SoundStudio" (see the "working" file.
Best regards,
Wilfried

[Link](https://www.dropbox.com/scl/fo/vq1qk2rtbrbk3pvaa92bh/ABJPR36CHOEwQVxUbP4EX_Q?rlkey=fbqejpli465xjg23jazcjl1ue&dl=0)

**Comment by CountryTec** [comment]
And btw you can make the export to eBird working by just leaving the first line with the attribute names away. Did use the file (also stored in same folder) and removed 1st line which did allow to import to eBird. ;) Wilfried

**Comment by Mattk70** [comment]
HI @CountryTec , I'll take a look.  It sounds like there's something different about this file's header. The BEXT/iXML standard doesn't specify a limit, so maybe this one is longer, we'll see.

As for the eBird header row, this is intentional, in case you want to add information to the export that isn't supplied by Chirpity. I do say in the docs "Help > whaat's an eBird record" that you need to remove that row before upload.

**Comment by CountryTec** [comment]
<img width="538" alt="Bildschirmfoto 2024-04-12 um 13 21 31" src="https://github.com/Mattk70/Chirpity-Electron/assets/165419572/201ea172-047a-4688-b030-b6b4ceff3e0c">

Dear Matt, downloaded and installed V1.69.
Amazing, all works fine with files from F6 and no "workaround". It did 10 files of 96 KhZ 32 Bit and 2.15 GB each in just 108 seconds. 
Much appreciated.
