### ISSUE TITLE
Normalise not functioning after update to 1.6.8

### ISSUE THREAD

**Issue by aasyvind** [Mattk70/Chirpity-Electron#87]
When listening to my recordings I have been using "Normalise Audio" and a High Pass filter at 250Hz. After updating to version 1.6.8 these filters are not functioning together, making it impossible to listen to the recording (the whole sonogram turns red). The filters seem to be working separately, but not together.

**Comment by Mattk70** [comment]
Hi @aasyvind. Oh dear. I'm sorry to hear you are having this issue. It works as expected when I try this filter combination.

Do you have the filters enabled? If they are enabled the icon will be yellow, like this:

![image](https://github.com/Mattk70/Chirpity-Electron/assets/61826357/7dd73d87-e459-4108-b942-aed17b49282a)

If this isn't your issue, perhaps you might share
1. A screenshot of the issue
2. Your OS (Mac / PC)
3. A file that exhibits this problem

Many thanks!

**Comment by aasyvind** [comment]
Thank you for the quick reply! See screenshots below of a redwing from tonight. I was not able to attach the file, because the type was not supported (FLAC). 

Normalise, no filter:
![image](https://github.com/Mattk70/Chirpity-Electron/assets/165548995/2bc4b802-1d04-4196-b978-a479c1b0c645)

High pass filter, no normalise:
![image](https://github.com/Mattk70/Chirpity-Electron/assets/165548995/556c117c-084f-40d3-b576-7deb30eb38ce)

High pass fiter and normalise:
![image](https://github.com/Mattk70/Chirpity-Electron/assets/165548995/29e168e7-bb80-429f-bb72-0b51eff71479)

As you can see from the colour in the last screenshot, something is wrong. I use a PC. I did not do any changes manually to the settings that was working before, I only updated to the new version.

**Comment by Mattk70** [comment]
This looks correct? Normalise 'stretches' the amplitude in the audio, such that the quietest signal is close to zero, and the loudest is close to 1 (maximum volume) . In the first screenshot, the loudest frequencies are in the 0-250Hz range, so normalise has little effect on the higher frequencies. In the second, the low frequency amplitude has been removed. In the third, now there is no high amplitude, low frequency noise, the higher frequencies get an amplitude boost.

The change to the behaviour is because now the cut filters are applied _before_ normalisation if both are active. If you wanted to have "less" normalisation, you could use the low shelf filter, and adjust the amount of attenuation until you were happy with the sound output.

**Comment by aasyvind** [comment]
No, there is a big difference from former versions. I uninstalled 1.6.8 and installed 1.6.0 instead now. This is the same file with high pass filter and normalise in 1.6.0:
![image](https://github.com/Mattk70/Chirpity-Electron/assets/165548995/bc0638e9-9354-497f-a5a1-7d5f962acea6)

**Comment by Mattk70** [comment]
_This_ looks like it is not working. The audio has not been normalised

**Comment by aasyvind** [comment]
Hm, there is a difference between the recording before or after normalisation in the old version. Without normalisation:
![image](https://github.com/Mattk70/Chirpity-Electron/assets/165548995/4585386c-857d-4b31-b39b-afb2046f5927)
With normalisation:
![image](https://github.com/Mattk70/Chirpity-Electron/assets/165548995/6fea61c8-02c6-4c6b-9d96-cf72169b87b7)

Of couse I have no idea how it is supposed to be, but the old version is pretty close to the normalised output from Audacity. The one from the new version is impossible to listen to.

**Comment by Mattk70** [comment]
I agree, I think the new way is the correct approach. It's not a waste of my time, it's good to know how people respond to the changes!

As I said, you can moderate the effect of the normalisation by using the low shelf filter and adjusting that attenuation applied. An alternative, which will produce results similar to previous versions would be to apply the high shelf filter and adjust the volume using the slider until the results are as you like.
