### ISSUE TITLE
No audio when exporting a call

### ISSUE THREAD

**Issue by JoostvanBruggen** [Mattk70/Chirpity-Electron#92]
When I have a nice recording I's like to save it on my computer.
But when I right click and try to save the selected part of the audio there is nothing in the recording. The file is 0kb.

It never worked. How do I save a selection of the recording?

**Comment by Mattk70** [comment]
This works fine for me. Could you describe or better, post a screenshot of your audio export settings? Also it may be helpful to know the properties of your source file(s) - things like the recorder used, file format, sample rate. I'd like to find a way to reproduce this error. Thanks!

**Comment by JoostvanBruggen** [comment]
https://github.com/Mattk70/Chirpity-Electron/assets/166588497/0458b532-0295-4da3-b2ad-9b5db49022dc

Maybe you can look at this screen-recording?

Joost

**Comment by Mattk70** [comment]
Thanks Joost. I have tracked down the issue, which is a bug in the filter settings. You can work around this and export files if you add a value to the low shelf filter (you can leave attenuation at zero - it will not affect the audio at all). Ffmpeg (the conversion module) complains when filters are active and the low shelf filter threshold is zero.

**Comment by JoostvanBruggen** [comment]
yes it works now like yopu've suggested!
