### ISSUE TITLE
It doesn't save to Archive

### ISSUE THREAD

**Issue by Vollpflock** [Mattk70/Chirpity-Electron#97]
**Describe the bug**
It doesn't save to Archive anymore. I'm sure it's just on my end, but maybe you know what the issue is?

**To Reproduce**
1. Analyze file
2. Save to archive
3. It does nothing. When I edit a record, an exclamation mark shows up. Cmd+S won't do anything. 

**Expected behavior**
It should be saved to archive. 

What I tried:
Quitting the app
Restarting
Installing an older version (I think 1.6.4)
Removing all chirpity files in library and reinstalling chirpity

**Screenshots**
![Screenshot 2024-04-10 at 10 51 19](https://github.com/Mattk70/Chirpity-Electron/assets/26574621/5ac3cb37-9b48-495f-9ce2-9fe0d5473911)

**Additional context**
V1.6.8, M1 mac

**Comment by Mattk70** [comment]
I *think* this may be an issue with the warning not being cleared when you save to archive after editing a record. Can you check? Are the records actually saved, or not? When I edited a record and saved the results, the warning remained, but the records were saved.

**Comment by Vollpflock** [comment]
Thank you. No, nothing gets saved. It doesn't do or save anything if I click on "Save to Archive" or hit cmd+S

**Comment by Mattk70** [comment]
OK - I think I have found the issue. I'll add a fix to 1.6.9, which I am about to release...

**Comment by Vollpflock** [comment]
It's working great now, thanks!
