### ISSUE TITLE
After editing a record, it resets to the first species alphabetically

### ISSUE THREAD

**Issue by Vollpflock** [Mattk70/Chirpity-Electron#99]
**Is your feature request related to a problem? Please describe.**
After editing a record, it resets to the first species alphabetically (returning to the starting point). It should remain in its current position. For example, if I edit a record for a Eurasian Whimbrel, I don't want it to revert back to 'Alpine Chough'.

**Describe the solution you'd like**
Staying at the same position.

**Comment by Mattk70** [comment]
Sorry, what's 'it' in this issue?

**Comment by Vollpflock** [comment]
Maybe the selection? So if I select Eurasian Whimbrel, I want it to stay there after editing a Eurasian Whimbrel-record. I don't want it to select the first species in the alphabet automatically (f.e. Alpine Chough).

**Comment by Mattk70** [comment]
Do you mean the species summary table scrolls to the top? That's not supposed to happen and I'll dig into why.

**Comment by Vollpflock** [comment]
Exactly.

**Comment by Mattk70** [comment]
I've fixed this. It'll go in the next release.

**Comment by Mattk70** [comment]
Fixed in 1.7.0
